name: maven-ci
author: jactor-rises
description: A maven build using a docker container

inputs:
  workpath:
    description: File path to the folder containing the pom.xml
    required: true
  artifact:
    description: Name of the artifact beeing build
    required: true
  image:
    description: Name of the docker container to use
    required: false
    default: 'maven:3.6.2-jdk-12'

using: 'shell'
runs: 'docker run -rm helloworld'
# runs: 'docker run -it -rm --name $INPUT_ARTIFACT -v $INPUT_WORKPATH:/usr/src/maven -w /usr/src/mymaven $INPUT_IMAGE mvn -B package'
