name: continious integration on features
on:
  push:
    branches:
      - '**'
      - '!master'

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - name: init
        uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - uses: actions/setup-java@v1
        with:
          java-version: '12'
      - name: debug
        run: env
      - name: cache maven dependencies
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Verify that no dependencies are of type SNAPSHOT
        uses: navikt/bidrag-actions/verify-mvn-dependencies@master
      - id: prepare
        name: prepare release of maven package
        uses: navikt/bidrag-actions/release-prepare-for-mvn@master
        env:
          NEW_SNAPSHOT_VERSION_FILE: .new-snapshot-version
          RELEASE_VERSION_FILE: .release-version
      - run: "echo ${{ steps.prepare.outputs.release-version }}"
      - name: build & test with maven
        run: |
          mvn -B install
