name: continious integration
on:
  push:
    branches:
      - '!master'
  pull_request:
    branches:
      - master

jobs:
  ci-maven:
    runs-on: ubuntu-latest

    steps:
      - name: debug
        runs: env
      - name: init
        uses: actions/checkout@v1
      - name: build & test with maven
        uses: shell
        runs: 'docker run -it --rm --name jactor-persistence -v $GITHUB_WORKSPACE:/jactor-persistence:/usr/src/mymaven -w /usr/src/mymaven maven:3.6.2-jdk-12 mvn install'
