name: continious integration
on:
  push:
    branches:
      - '!master'
  pull_request:
    branches:
      - master

jobs:
  ci-maven:
    runs-on: ubuntu-latest

    steps:
      - name: init
        uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: debug
        run: env
      - uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: build & test with maven
        env:
          ARTIFACT: 'bidrag-commons'
          IMAGE: 'maven:3.6.2-jdk-12'
          M2_REPO: '~/.m2/repository'
        run: |
          docker run --rm --name "$ARTIFACT" \
            -v "$M2_REPO":/root/.m2 \
            -v "$PWD":/usr/src/maven \
            -w /usr/src/maven "$IMAGE" mvn -B install
