name: continious integration
on:
  push:
    branches:
      - '!master'
  pull_request:
    branches:
      - master

jobs:
  ci-maven:
    runs-on: ubuntu-latest

    steps:
      - name: debug
        run: env
      - name: init
        uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: build & test with maven
        uses: ./.github/actions/maven-ci'
        with:
          workpath: $GITHUB_WORKSPACE/bidrag-commons
          image: 'maven:3.6.2-jdk-12'
          artifact: 'bidrag-commons'
